### ISSUE TITLE
Question Regarding Figure 3 in the Paper

### ISSUE THREAD

**Issue by hezhiyang2000** [ming053l/DRCT#25]
In the paper, Figure 3 describes the deep feature extraction part as consisting of several RDG modules. According to the paper, an RDG module is composed of multiple SDRCB modules, and each SDRCB module, in turn, includes several STL, Conv, Leaky ReLU, and Concat layers. However, when I looked at the code, the structure labeled as RDG appears to match the description of SDRCB from the paper. Could there be an error in the description of the layers?

Please let me know if there's a mistake, or if I'm misunderstanding something.

**Comment by linanfang115** [comment]
I also found this issue

**Comment by linanfang115** [comment]
I also found this problem

**Comment by ming053l** [comment]
hi, i have updated the correct figure3 and corresponding description of DRCT in Arxiv. Sorry for any inconvenience, thanks!
