### ISSUE TITLE
Real-DRCT-GAN_Finetuned from MSE only in onnx. Author removed pth. Anyone have pytorch weight backup?

### ISSUE THREAD

**Issue by zelenooki87** [ming053l/DRCT#28]
Does anyone by any chance have a backed-up PyTorch model "Real-DRCT-GAN_Finetuned from MSE" : 
![SNAG-0003](https://github.com/user-attachments/assets/9f826914-067d-466f-be94-3a9815241d45)
https://drive.google.com/file/d/1DnEb1G58xumuMmXoqiLG2lbYZOVbz_Kp/view?usp=drive_link
The author @ming053l  deleted the file from Google Drive.

Here are my backed up onnx in onnx 16.
https://mega.nz/file/0gJwyIBA#fTdbXWb6zbWrQApg2VgNRbY_fh3wdy5f-mP4Oz1jVbU

You could run it with this script:
https://pastebin.com/DUAKpuF1

Or within chainner.

Anyway, pytorch weight would be nice to have.

**Comment by ming053l** [comment]
Hi, sorry for inconvinece.

The checkpoint of  "Real-DRCT-GAN_Finetuned from MSE" somehow losses in my Googledrive. So the link on github was going to be invalid.

I will retrain a new one and update the link on repository as soon as possible, thanks!

**Comment by zelenooki87** [comment]
And one more question, please. When we can expect DRCT v2 to be released?  Thank you very much!

**Comment by zelenooki87** [comment]
Hi @ming053l . Are there any hints about a re-upload of the Real-DRCT-GAN_Finetuned from MSE model? If you can send it to me, please do :) Also, what's the status of DRCT v2, how's the progress, and when can we expect it to be released on GitHub? Thank you very much.

**Comment by zelenooki87** [comment]
Hi, @ming053l  Please answer :)
Thanks

**Comment by ming053l** [comment]
您好，抱歉回覆晚了，我沒有註意到該電子郵件。

Real-DRCT-GAN已經準備好了，稍後再更新。

Real-DRCT-GAN 現在正在訓練中。

由於伺服器問題，我們的訓練過程中斷了一個星期。現在已修復並運行良好

我認為 FractalDRCT (v2) 將於 2025 年 1 月發布。

Best Regards

[image: 圖片.png]

zelenooki87 ***@***.***> 於 2024年12月3日 週二 上午3:35寫道：

**Comment by ming053l** [comment]
hi, Real-DRCT-GAN have already updated in google drive, if there are any questions, please let me know! thanks

And Real-DRCT-GAN is still training, almost 1~2 days
