### ISSUE TITLE
论文中的RDG block和代码中实现不同

### ISSUE THREAD

**Issue by linanfang115** [ming053l/DRCT#29]
作者你好，
论文中的结构图显示RGD block是由多个SDRCB构成，每个RGD 的SDRCB数量应该由depth列表定义，但是代码DRCT_arch.py中并未使用depth列表（如：depth[i_layer]）。从代码中定义的模型结构可以看出RGD block仅由5个STL和相关的处理层构成。

**Comment by ming053l** [comment]
你好，感謝您的仔細檢查，這個確實是論文多寫了沒有錯，這個是我的疏忽，我會在這幾天上傳更新正確的內容到arXiv上。

謝謝!

**Comment by ming053l** [comment]
您好，前幾天已更新正確版本至Arxiv，若有造成不便請您見諒，謝謝
