### ISSUE TITLE
How to do the pretraining

### ISSUE THREAD

**Issue by wfz666** [ming053l/DRCT#30]
Hi, can anyone tell me how to do the pretraining on imagenet? Is it the same as training and I only need to modify the data direct? Thanks!

**Comment by ming053l** [comment]
hi, please follow basicsr's repository for dataset preparation. 

https://github.com/XPixelGroup/BasicSR/blob/master/docs/DatasetPreparation.md

Pretraining-step is important for DRCT. 

According to our experiment, just training on DF2K may lead to unstablization or unsatisfactory results
