### ISSUE TITLE
Why there is not Channel Atention in DRCT ?

### ISSUE THREAD

**Issue by RayTan183** [ming053l/DRCT#5]
Thanks for your contribution.  I am curious that why  there is not Channel Atention in DRCT comparing to HAT. Is it due to considerations of model complexity and performance？ Does it has some experimental evidence? Thank you.

**Comment by ming053l** [comment]
Hello. Sorry for lately relpy.

Yes, your considerations are correct. To some extent, using channel attention and Hybrid attention (in HAT or the other SOTA SR methods) to activate more pixels can further improve SR model performance. Similarly, in the NTIRE2024 Challenge, a team coupled MambaIR (SS2D) and HAT and achieved very great results. However, this may result in a higher computational burden.

The simple idea is that we hope to tell everyone that it is feasible to introduce dense-connection in SR models such as Swin-IR and should be promoted.
